version: '3'
services:

################################################  HDFS ############################################
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - /tmp/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
    networks:
      net_pet:
        ipv4_address: 172.27.1.5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - /tmp/hdfs/datanode:/hadoop/dfs/data
      - ./bank:/bank
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50075:50075"
    networks:
      net_pet:
        ipv4_address: 172.27.1.6


################################################  HIVE ############################################

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    networks:
      net_pet:
        ipv4_address: 172.27.1.7

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    networks:
      net_pet:
        ipv4_address: 172.27.1.8

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    depends_on:
      - datanode
    networks:
      net_pet:
        ipv4_address: 172.27.1.9

################################################  SPARK ############################################

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    env_file:
      - ./hadoop-hive.env
    networks:
      net_pet:
        ipv4_address: 172.27.1.10

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    env_file:
      - ./hadoop-hive.env
    networks:
      net_pet:
        ipv4_address: 172.27.1.11

################################################  ZOOKEEPER #########################################
  zookeeperKafka:
    hostname: zookeeperKafka
    container_name: zookeeperKafka
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2182:2182"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=2182
    networks:
      net_pet:
        ipv4_address: 172.27.1.13

  zookeeper:
    hostname: zookeeperNifi
    container_name: zookeeperNifi
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      net_pet:
        ipv4_address: 172.27.1.14
################################################  KAFKA ############################################
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.27.1.16
      KAFKA_ZOOKEEPER_CONNECT: zookeeperKafka:2182
    networks:
      net_pet:
        ipv4_address: 172.27.1.16

################################################  NIFI ############################################
  nifi:
    image: apache/nifi:1.11.4
    container_name: nifi
    ports:
      - "9090:9090" # Unsecured HTTP Web Port
      - "22:22" #ssh
    environment:
      - NIFI_WEB_HTTP_PORT=9090
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeperNifi:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      - /home/fedesardo/data/nifi:/home/nifi/data
    networks:
      net_pet:
        ipv4_address: 172.27.1.12

################################################  ZEPPELIN  ########################################
  zeppelin:
    image: openkbs/docker-spark-bde2020-zeppelin
    container_name: zeppelin
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
      SPARK_MASTER: "spark://spark-master:7077"
      MASTER: "spark://spark-master:7077"
      SPARK_MASTER_URL: spark://spark-master:7077
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS:
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
    ports:
      - 19090:8080
    env_file:
      - ./hadoop-hive.env
    volumes:
      - /tmp/simple-demo/zeppelin/data:/usr/lib/zeppelin/data:rw
      - /tmp/simple-demo/zeppelin/notebook:/usr/lib/zeppelin/notebook:rw
    command: /usr/lib/zeppelin/bin/zeppelin.sh
#    depends_on:
#      spark-master:
#        condition: service_healthy
#      namenode:
#        condition: service_healthy
    networks:
      net_pet:
        ipv4_address: 172.27.1.15

################################################  POSTGRESQL  ########################################
  postgres-db:
    image: postgres:13.2
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_MULTIPLE_DATABASES: "${SUPERSET_POSTGRES_DB}"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - spotydash-network
    restart: always
    networks:
      net_pet:
        ipv4_address: 172.27.1.18


################################################  SUPERSET  ########################################
  superset:
    image: amancevice/superset
    entrypoint: bash /entrypoints/start_superset.sh
    restart: always
    depends_on:
      - postgres-db
      - redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FLASK_APP: ${FLASK_APP}
      SUPERSET_EMAIL: ${SUPERSET_EMAIL}
      SUPERSET_FIRSTNAME: ${SUPERSET_FIRSTNAME}
      SUPERSET_LASTNAME: ${SUPERSET_LASTNAME}
      SUPERSET_USER: ${SUPERSET_USER}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
      SUPERSET_PORT: ${SUPERSET_PORT}
      SUPERSET_POSTGRES_DB: ${SUPERSET_POSTGRES_DB}
      SUPERSET_REDIS_PORT: ${SUPERSET_REDIS_PORT}
    ports:
      - ${SUPERSET_PORT}:${SUPERSET_PORT}
    volumes:
      - type: bind
        source: ./
        target: /entrypoints
      - type: bind
        source: ../superset
        target: /superset
      - type: bind
        source: ../superset/superset_config.py
        target: /etc/superset/superset_config.py
    networks:
      - spotydash-network

  # REDIS
  redis:
    image: redis
    restart: always

# VOLUMES
volumes:
  postgres-data:

##########################################  NETWORKING ###########################################

networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
